spring.application.name=MarketLocalShirtsAPI

# Acceso a la base de datos MS SQL en somee
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://MarketLocalShirts.mssql.somee.com:1433;databaseName=MarketLocalShirts;encrypt=true;trustServerCertificate=true;
spring.datasource.username=VaDa1232_SQLLogin_11
spring.datasource.password=notm65zhm6


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# JWT
jwt.secret=MarketLocalShirtsApiClaveSecretaJwt2026EsfeProyecto
jwt.expiration=86400000